name: Quality

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  Quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Format
        run: npm run format:check
      - name: Build
        run: npm run build
